server: 
  port: 9000
spring: 
  application:  
    name: sport_system-sport_system #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://188.131.213.13:3306/sport_system?verifyServerCertificate=true&amp;useSSL=false&amp;useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: mindyu55
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true

